"""DataPrototypes module."""
from .parameter_data_prototype import ParameterDataPrototype
from .variable_data_prototype import VariableDataPrototype
from .autosar_data_prototype import AutosarDataPrototype
from .data_prototype import DataPrototype
from .application_array_element import ApplicationArrayElement
from .application_record_element import ApplicationRecordElement
from .application_composite_element_data_prototype import ApplicationCompositeElementDataPrototype

