"""AUTOSAR LEnum enumeration.

References:
  - AUTOSAR_FO_TPS_GenericStructureTemplate.pdf (page 350)

JSON Source: packages/M2_MSR_Documentation_TextModel_LanguageDataModel.enums.json"""

from __future__ import annotations

from armodel.models.M2.AUTOSARTemplates.GenericStructure.GeneralTemplateClasses.PrimitiveTypes.ar_enum import AREnum

class LEnum(AREnum):
    """AUTOSAR LEnum enumeration.

    This enum inherits from AREnum, which provides:
    - serialize(): XML serialization
    - deserialize(): XML deserialization with automatic member matching
    - Transparent equality comparison with string values
    """

    def __init__(self, value: str) -> None:
        """Initialize enum member.

        Args:
            value: The enum value as a string
        """
        self._value_ = value

    AA = "AA"
    AB = "AB"
    AF = "AF"
    AM = "AM"
    AR = "AR"
    AS = "AS"
    AY = "AY"
    AZ = "AZ"
    BA = "BA"
    BE = "BE"
    BG = "BG"
    BH = "BH"
    AUTOSA_RBI = "A-U-T-O-S-A-RBI"
    BN = "BN"
    BO = "BO"
    BR = "BR"
    CA = "CA"
    CO = "CO"
    CS = "CS"
    CY = "CY"
    DA = "DA"
    DE = "DE"
    DZ = "DZ"
    EL = "EL"
    EN = "EN"
    EO = "EO"
    ES = "ES"
    ET = "ET"
    EU = "EU"
    FA = "FA"
    FI = "FI"
    FJ = "FJ"
    FO = "FO"
    AUTOSAR = "A-U-T-O-S-A-R"
    FOR_ALL = "FOR-ALL"
    FR = "FR"
    FY = "FY"
    GA = "GA"
    GD = "GD"
    GL = "GL"
    GN = "GN"
    GU = "GU"
    HA = "HA"
    HI = "HI"
    HR = "HR"
    HU = "HU"
    HY = "HY"
    IA = "IA"
    IE = "IE"
    IKIN = "IKIN"
    IS = "IS"
    IT = "IT"
    IW = "IW"
    JA = "JA"
    JI = "JI"
    JW = "JW"
    KA = "KA"
    KK = "KK"
    KL = "KL"
    KM = "KM"
    KN = "KN"
    KO = "KO"
    KS = "KS"
    KU = "KU"
    KY = "KY"
    LA = "LA"
    LN = "LN"
    LO = "LO"
    LT = "LT"
    LV = "LV"
    MG = "MG"
    MI = "MI"
    MK = "MK"
    ML = "ML"
    MN = "MN"
    MO = "MO"
    MR = "MR"
    MS = "MS"
    MT = "MT"
    MY = "MY"
    NA = "NA"
    NE = "NE"
    NL = "NL"
    NO = "NO"
    OC = "OC"
    OM = "OM"
    PA = "PA"
    PL = "PL"
    PS = "PS"
    PT = "PT"
    QU = "QU"
    RM = "RM"
    RN = "RN"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    SA = "SA"
    SD = "SD"
    SG = "SG"
    SH = "SH"
    SI = "SI"
    SK = "SK"
    SL = "SL"
    SM = "SM"
    SN = "SN"
    SO = "SO"
    SQ = "SQ"
    SR = "SR"
    SS = "SS"
    ST = "ST"
    SU = "SU"
    SV = "SV"
    SW = "SW"
    TA = "TA"
    TE = "TE"
    TG = "TG"
    TH = "TH"
    TI = "TI"
    TK = "TK"
    TL = "TL"
    TN = "TN"
    TO = "TO"
    TR = "TR"
    TS = "TS"
    TT = "TT"
    TW = "TW"
    UK = "UK"
    UR = "UR"
    UZ = "UZ"
    VI = "VI"
    VO = "VO"
    WO = "WO"
    XH = "XH"
    YO = "YO"
    ZH = "ZH"
    ZU = "ZU"
