"""InstanceRefs module."""
from .variable_in_atomic_swc_instance_ref import VariableInAtomicSwcInstanceRef
from .r_variable_in_atomic_swc_instance_ref import RVariableInAtomicSwcInstanceRef
from .r_mode_in_atomic_swc_instance_ref import RModeInAtomicSwcInstanceRef
from .inner_port_group_in_composition_instance_ref import InnerPortGroupInCompositionInstanceRef
from .trigger_in_atomic_swc_instance_ref import TriggerInAtomicSwcInstanceRef
from .r_trigger_in_atomic_swc_instance_ref import RTriggerInAtomicSwcInstanceRef
from .p_trigger_in_atomic_swc_type_instance_ref import PTriggerInAtomicSwcTypeInstanceRef
from .operation_in_atomic_swc_instance_ref import OperationInAtomicSwcInstanceRef
from .r_operation_in_atomic_swc_instance_ref import ROperationInAtomicSwcInstanceRef
from .p_operation_in_atomic_swc_instance_ref import POperationInAtomicSwcInstanceRef
from .r_mode_group_in_atomic_swc_instance_ref import RModeGroupInAtomicSWCInstanceRef
from .p_mode_group_in_atomic_swc_instance_ref import PModeGroupInAtomicSwcInstanceRef
from .mode_group_in_atomic_swc_instance_ref import ModeGroupInAtomicSwcInstanceRef

