"""MultilanguageData module."""
from .multi_language_overview_paragraph import MultiLanguageOverviewParagraph
from .multilanguage_long_name import MultilanguageLongName
from .multi_language_paragraph import MultiLanguageParagraph
from .multi_language_verbatim import MultiLanguageVerbatim
from .multi_language_plain_text import MultiLanguagePlainText

