"""ReferrableSubtypesEnum AUTOSAR primitive type.

References:
  - AUTOSAR_FO_TPS_GenericStructureTemplate.pdf (page 73)

JSON Source: packages/M2_AUTOSARTemplates_GenericStructure_GeneralTemplateClasses_PrimitiveTypes.primitives.json"""

from __future__ import annotations
from typing import TYPE_CHECKING, Optional
import xml.etree.ElementTree as ET

from armodel2.models.M2.AUTOSARTemplates.GenericStructure.GeneralTemplateClasses.PrimitiveTypes.ar_primitive import ARPrimitive

# This primitive is a proxy for an enum generated by the MMT. It allows to refer to any subclass of Referrable. Due to technical reasons the possible values are not shown in this class table. Tags: xml.mds.type=REFERRABLE–SUBTYPES-ENUM xml.xsd.type=string Table 4.15: ReferrableSubtypesEnum [TPS_GST_00437] Existence of ReferenceBase.package and ReferenceBase. globalInPackage (cid:100)ReferenceBase.package and ReferenceBase.globalIn-
class ReferrableSubtypesEnum(ARPrimitive):
    """AUTOSAR ReferrableSubtypesEnum primitive type.

    Inherits deserialize() from ARPrimitive which automatically converts
    XML text content to the appropriate Python type based on python_type.
    """

    python_type: type = str
    """The underlying Python type for this primitive."""

    def __init__(self, value: Optional[str] = None) -> None:
        """Initialize ReferrableSubtypesEnum.

        Args:
            value: The primitive value
        """
        super().__init__()
        self.value: Optional[str] = value
