"""AttributeValueVariationPoints module."""
from .numerical_value_variation_point import NumericalValueVariationPoint
from .attribute_value_variation_point import AttributeValueVariationPoint
from .abstract_numerical_variation_point import AbstractNumericalVariationPoint
from .boolean_value_variation_point import BooleanValueVariationPoint
from .float_value_variation_point import FloatValueVariationPoint
from .integer_value_variation_point import IntegerValueVariationPoint
from .limit_value_variation_point import LimitValueVariationPoint
from .positive_integer_value_variation_point import PositiveIntegerValueVariationPoint
from .unlimited_integer_value_variation_point import UnlimitedIntegerValueVariationPoint
from .time_value_value_variation_point import TimeValueValueVariationPoint
from .abstract_enumeration_value_variation_point import AbstractEnumerationValueVariationPoint
from .enumeration_mapping_entry import EnumerationMappingEntry
from .enumeration_mapping_table import EnumerationMappingTable

