"""Mode_0x0A_RequestEmissionRelated module."""
from .diagnostic_request_emission_related_dtc_permanent_status import DiagnosticRequestEmissionRelatedDTCPermanentStatus
from .diagnostic_request_emission_related_dtc_permanent_status_class import DiagnosticRequestEmissionRelatedDTCPermanentStatusClass

