"""InstanceRefs module."""
from .component_in_system_instance_ref import ComponentInSystemInstanceRef
from .operation_in_system_instance_ref import OperationInSystemInstanceRef
from .variable_data_prototype_in_system_instance_ref import VariableDataPrototypeInSystemInstanceRef
from .trigger_in_system_instance_ref import TriggerInSystemInstanceRef
from .port_group_in_system_instance_ref import PortGroupInSystemInstanceRef

