"""InstanceRef module."""
from .inner_data_prototype_group_in_composition_instance_ref import InnerDataPrototypeGroupInCompositionInstanceRef
from .inner_runnable_entity_group_in_composition_instance_ref import InnerRunnableEntityGroupInCompositionInstanceRef
from .runnable_entity_in_composition_instance_ref import RunnableEntityInCompositionInstanceRef
from .variable_data_prototype_in_composition_instance_ref import VariableDataPrototypeInCompositionInstanceRef

