"""ReferrableSubtypesEnum primitive type."""

# This primitive is a proxy for an enum generated by the MMT. It allows to refer to any subclass of Referrable. Due to technical reasons the possible values are not shown in this class table. Tags: xml.mds.type=REFERRABLE–SUBTYPES-ENUM xml.xsd.type=string Table 4.15: ReferrableSubtypesEnum [TPS_GST_00437] Existence of ReferenceBase.package and ReferenceBase. globalInPackage (cid:100)ReferenceBase.package and ReferenceBase.globalIn-
ReferrableSubtypesEnum = str
