"""Mode_0x08_RequestControlOfOnBoard module."""
from .diagnostic_request_control_of_on_board_device import DiagnosticRequestControlOfOnBoardDevice
from .diagnostic_request_control_of_on_board_device_class import DiagnosticRequestControlOfOnBoardDeviceClass
from .diagnostic_test_routine_identifier import DiagnosticTestRoutineIdentifier

